Feature/generate sso
cubie-dev/cube-backend pull request #32
Opened 2021-09-15 12:22 UTC by Matthijskl

2021-09-15 14:23 UTC, emachiels commented on app/Http/Controllers/UserController.php
> +        throw new HttpException(400);
BadRequestHttpException

2021-09-15 14:24 UTC, emachiels commented on app/Http/Controllers/UserController.php
> +    public function generateAuthTicket(Request $request): JsonResponse
gebruik request uit constructor DI

2021-09-15 14:25 UTC, emachiels commented on app/Managers/User/UserManager.php
> +        $authTicket = "Cube-" . bin2hex(random_bytes(24));
die uniqueid was best wel nice

2021-09-15 14:25 UTC, emachiels commented on app/Managers/User/UserManager.php
> +    public function createAuthTicket(User $user): string | null
: ?string

2021-09-15 14:25 UTC, emachiels commented on routes/api.php
> +        $user->get('auth-ticket', [UserController::class, 'generateAuthTicket']);
post of patch

2021-09-15 14:26 UTC, Matthijskl commented on app/Managers/User/UserManager.php
> +        $authTicket = "Cube-" . bin2hex(random_bytes(24));
Omdat dat volgens @merjn geen veilige functie was.

2021-09-15 16:10 UTC, merjn commented on app/Repository/User/UserRepository.php
> +        return $user->update([
Je hoeft geen aparte methode hiervoor aan te maken, omdat `model->push()` of `model->save()` hetzelfde doet. Repositories zijn zo al snel bloated. Kan dan gewoon in je manager.

2021-09-15 16:12 UTC, merjn requested changes
Naast Erans review vind ik dat je gebruik moet maken van je base repository om dingen te updaten. Zo wordt het naar mijn mening nogal bloated.

2021-09-26 13:36 UTC, merjn approved these changes

2021-09-27 11:45 UTC, merged